/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AziendaRouteImport } from './routes/azienda'
import { Route as CertificazioniRouteImport } from './routes/certificazioni'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MilanoUnitedRouteImport } from './routes/milano-united'
import { Route as ReferenzeRouteImport } from './routes/referenze'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCertificazioniRouteImport } from './routes/admin.certificazioni'
import { Route as AdminContenutiRouteImport } from './routes/admin.contenuti'
import { Route as AdminLeadRouteImport } from './routes/admin.lead'
import { Route as AdminReferenzeRouteImport } from './routes/admin.referenze'
import { Route as AdminSettoriRouteImport } from './routes/admin.settori'
import { Route as AdminSezioniRouteImport } from './routes/admin.sezioni'
import { Route as SettoriIndexRouteImport } from './routes/settori.index'
import { Route as SettoriSlugRouteImport } from './routes/settori.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AziendaRoute = AziendaRouteImport.update({
  id: '/azienda',
  path: '/azienda',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificazioniRoute = CertificazioniRouteImport.update({
  id: '/certificazioni',
  path: '/certificazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MilanoUnitedRoute = MilanoUnitedRouteImport.update({
  id: '/milano-united',
  path: '/milano-united',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzeRoute = ReferenzeRouteImport.update({
  id: '/referenze',
  path: '/referenze',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificazioniRoute = AdminCertificazioniRouteImport.update({
  id: '/certificazioni',
  path: '/certificazioni',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContenutiRoute = AdminContenutiRouteImport.update({
  id: '/contenuti',
  path: '/contenuti',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadRoute = AdminLeadRouteImport.update({
  id: '/lead',
  path: '/lead',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferenzeRoute = AdminReferenzeRouteImport.update({
  id: '/referenze',
  path: '/referenze',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettoriRoute = AdminSettoriRouteImport.update({
  id: '/settori',
  path: '/settori',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSezioniRoute = AdminSezioniRouteImport.update({
  id: '/sezioni',
  path: '/sezioni',
  getParentRoute: () => AdminRoute,
} as any)
const SettoriIndexRoute = SettoriIndexRouteImport.update({
  id: '/settori/',
  path: '/settori/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettoriSlugRoute = SettoriSlugRouteImport.update({
  id: '/settori/$slug',
  path: '/settori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/azienda': typeof AziendaRoute
  '/certificazioni': typeof CertificazioniRoute
  '/contatti': typeof ContattiRoute
  '/login': typeof LoginRoute
  '/milano-united': typeof MilanoUnitedRoute
  '/referenze': typeof ReferenzeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/certificazioni': typeof AdminCertificazioniRoute
  '/admin/contenuti': typeof AdminContenutiRoute
  '/admin/lead': typeof AdminLeadRoute
  '/admin/referenze': typeof AdminReferenzeRoute
  '/admin/settori': typeof AdminSettoriRoute
  '/admin/sezioni': typeof AdminSezioniRoute
  '/settori/$slug': typeof SettoriSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/settori/': typeof SettoriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/azienda': typeof AziendaRoute
  '/certificazioni': typeof CertificazioniRoute
  '/contatti': typeof ContattiRoute
  '/login': typeof LoginRoute
  '/milano-united': typeof MilanoUnitedRoute
  '/referenze': typeof ReferenzeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/certificazioni': typeof AdminCertificazioniRoute
  '/admin/contenuti': typeof AdminContenutiRoute
  '/admin/lead': typeof AdminLeadRoute
  '/admin/referenze': typeof AdminReferenzeRoute
  '/admin/settori': typeof AdminSettoriRoute
  '/admin/sezioni': typeof AdminSezioniRoute
  '/settori/$slug': typeof SettoriSlugRoute
  '/admin': typeof AdminIndexRoute
  '/settori': typeof SettoriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/azienda': typeof AziendaRoute
  '/certificazioni': typeof CertificazioniRoute
  '/contatti': typeof ContattiRoute
  '/login': typeof LoginRoute
  '/milano-united': typeof MilanoUnitedRoute
  '/referenze': typeof ReferenzeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/certificazioni': typeof AdminCertificazioniRoute
  '/admin/contenuti': typeof AdminContenutiRoute
  '/admin/lead': typeof AdminLeadRoute
  '/admin/referenze': typeof AdminReferenzeRoute
  '/admin/settori': typeof AdminSettoriRoute
  '/admin/sezioni': typeof AdminSezioniRoute
  '/settori/$slug': typeof SettoriSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/settori/': typeof SettoriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/azienda'
    | '/certificazioni'
    | '/contatti'
    | '/login'
    | '/milano-united'
    | '/referenze'
    | '/sitemap.xml'
    | '/admin/certificazioni'
    | '/admin/contenuti'
    | '/admin/lead'
    | '/admin/referenze'
    | '/admin/settori'
    | '/admin/sezioni'
    | '/settori/$slug'
    | '/admin/'
    | '/settori/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/azienda'
    | '/certificazioni'
    | '/contatti'
    | '/login'
    | '/milano-united'
    | '/referenze'
    | '/sitemap.xml'
    | '/admin/certificazioni'
    | '/admin/contenuti'
    | '/admin/lead'
    | '/admin/referenze'
    | '/admin/settori'
    | '/admin/sezioni'
    | '/settori/$slug'
    | '/admin'
    | '/settori'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/azienda'
    | '/certificazioni'
    | '/contatti'
    | '/login'
    | '/milano-united'
    | '/referenze'
    | '/sitemap.xml'
    | '/admin/certificazioni'
    | '/admin/contenuti'
    | '/admin/lead'
    | '/admin/referenze'
    | '/admin/settori'
    | '/admin/sezioni'
    | '/settori/$slug'
    | '/admin/'
    | '/settori/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AziendaRoute: typeof AziendaRoute
  CertificazioniRoute: typeof CertificazioniRoute
  ContattiRoute: typeof ContattiRoute
  LoginRoute: typeof LoginRoute
  MilanoUnitedRoute: typeof MilanoUnitedRoute
  ReferenzeRoute: typeof ReferenzeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SettoriSlugRoute: typeof SettoriSlugRoute
  SettoriIndexRoute: typeof SettoriIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azienda': {
      id: '/azienda'
      path: '/azienda'
      fullPath: '/azienda'
      preLoaderRoute: typeof AziendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificazioni': {
      id: '/certificazioni'
      path: '/certificazioni'
      fullPath: '/certificazioni'
      preLoaderRoute: typeof CertificazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milano-united': {
      id: '/milano-united'
      path: '/milano-united'
      fullPath: '/milano-united'
      preLoaderRoute: typeof MilanoUnitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenze': {
      id: '/referenze'
      path: '/referenze'
      fullPath: '/referenze'
      preLoaderRoute: typeof ReferenzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificazioni': {
      id: '/admin/certificazioni'
      path: '/certificazioni'
      fullPath: '/admin/certificazioni'
      preLoaderRoute: typeof AdminCertificazioniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contenuti': {
      id: '/admin/contenuti'
      path: '/contenuti'
      fullPath: '/admin/contenuti'
      preLoaderRoute: typeof AdminContenutiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lead': {
      id: '/admin/lead'
      path: '/lead'
      fullPath: '/admin/lead'
      preLoaderRoute: typeof AdminLeadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referenze': {
      id: '/admin/referenze'
      path: '/referenze'
      fullPath: '/admin/referenze'
      preLoaderRoute: typeof AdminReferenzeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settori': {
      id: '/admin/settori'
      path: '/settori'
      fullPath: '/admin/settori'
      preLoaderRoute: typeof AdminSettoriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sezioni': {
      id: '/admin/sezioni'
      path: '/sezioni'
      fullPath: '/admin/sezioni'
      preLoaderRoute: typeof AdminSezioniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/settori/': {
      id: '/settori/'
      path: '/settori'
      fullPath: '/settori/'
      preLoaderRoute: typeof SettoriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settori/$slug': {
      id: '/settori/$slug'
      path: '/settori/$slug'
      fullPath: '/settori/$slug'
      preLoaderRoute: typeof SettoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCertificazioniRoute: typeof AdminCertificazioniRoute
  AdminContenutiRoute: typeof AdminContenutiRoute
  AdminLeadRoute: typeof AdminLeadRoute
  AdminReferenzeRoute: typeof AdminReferenzeRoute
  AdminSettoriRoute: typeof AdminSettoriRoute
  AdminSezioniRoute: typeof AdminSezioniRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCertificazioniRoute: AdminCertificazioniRoute,
  AdminContenutiRoute: AdminContenutiRoute,
  AdminLeadRoute: AdminLeadRoute,
  AdminReferenzeRoute: AdminReferenzeRoute,
  AdminSettoriRoute: AdminSettoriRoute,
  AdminSezioniRoute: AdminSezioniRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AziendaRoute: AziendaRoute,
  CertificazioniRoute: CertificazioniRoute,
  ContattiRoute: ContattiRoute,
  LoginRoute: LoginRoute,
  MilanoUnitedRoute: MilanoUnitedRoute,
  ReferenzeRoute: ReferenzeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SettoriSlugRoute: SettoriSlugRoute,
  SettoriIndexRoute: SettoriIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
